### PR TITLE
Clean file directory and navbar

### PR DESCRIPTION
**Pull request by GitRengeki**
### File Directory
- The CSS folder created moved, and relative path links fixed
- JS folder created moved, and relative path links fixed

### Navbar Cleaning
- Fix _navbar-related HTML_ scripts. Wiped out unused structures in the `discord button`.
- Fix _navbar-related CSS_ scripts. I wiped out some scripts that overstyled the navbar.

### Globalized Customization
- Created a `:root` script for global customization. It includes `font-family` to eliminate repetitive scripts.

> I recommend using a collapsible navbar for mobile responsiveness

**The navbar requires a little more responsiveness and cleaning. It is still not fixed**

### CODE REVIEW

**Review by Harleythetech — APPROVED** [review]

**Comment by Harleythetech** [comment]
I got confused and decided to delete stuff but it's fixed now! please do a fetch merge on your side.

**Comment by Harleythetech** [comment]
Update: Looking at the code you were behind by a couple of codes. i have added and have been experimenting with responsiveness.

**Comment by Harleythetech** [comment]
one more thing: navigation bar it looks broken after checking.

**Review by Harleythetech — COMMENTED** [review]
CSS needs fix, Index out of date

**Comment by GitRengeki** [comment]
Thanks for the response. I'm working on improving the navbar.

**Comment by Harleythetech** [comment]
Welcome! just do the same thing when you have some improvements or something new to add!

**Comment by Harleythetech** [comment]
Kindly Check your Email (the one used in this account) as i have added you as one of the members of this community.

**Pull request merged**
